neo4j_uri = "bolt://192.168.41.129:7687"
neo4j_user = "neo4j"
neo4j_password = "Presentchezneo4j12fois$"
n4j_uri = "neo4j+s://accidentdelaroute.databases.neo4j.io"

neo4j_auradb = "h2T5L7wU3FC_rqojwpK8lRTjceJv1dEbKWBNnt4I9BA"

neo4j_auradb_uri = "neo4j+s://ce16f191.databases.neo4j.io"

host_url = "ssh mxmd@192.168.41.129"